SECTIONS_TO_IGNORE = [
    'TITLE',
    'CICLO OTTO',
    'Conteúdos',
    'INTRODUÇÃO',
    'BIBLIOGRAFIA',
    'MECÂNICA DE VEÍCULOS LEVES',
    'SUMÁRIO',
    'INTRODUÇÃO',
    'METROLOGIA PARA MECÂNICA AUTOMOTIVA',
    'APRESENTAÇÃO',
    'REFERÊNCIAS',
    'REFERÊNCIAS BIBLIOGRÁFICAS'
]
